Process Consumer-24:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.03-realization-3.pkl
0.1 0.101694915254
Process Consumer-17:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Consumer-25:
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.01-realization-6.pkl
0.1 0.101694915254
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.03-realization-4.pkl
0.1 0.101694915254
Process Consumer-31:
Process Consumer-16:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.05-realization-0.pkl
0.1 0.101694915254
Process Consumer-13:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.01-realization-2.pkl
0.1 0.101694915254
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.01-realization-5.pkl
0.1 0.101694915254
Process Consumer-30:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Process Consumer-22:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.03-realization-1.pkl
0.1 0.101694915254
Process Consumer-27:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
Process Consumer-15:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.03-realization-6.pkl
0.1 0.101694915254
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Process Consumer-14:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.01-realization-3.pkl
0.1 0.101694915254
Process Consumer-50:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
Process Consumer-12:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Consumer-49:
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Traceback (most recent call last):
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.01-realization-4.pkl
0.1 0.101694915254
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.01-realization-1.pkl
0.1 0.101694915254
AttributeError: 'Task_generate_rf' object has no attribute 'E'
Process Consumer-20:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Consumer-28:
Traceback (most recent call last):
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.07-realization-8.pkl
0.1 0.101694915254
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Process Consumer-33:
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Process Consumer-6:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    self.run()
Process Consumer-10:
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.05-realization-2.pkl
0.1 0.101694915254
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.03-realization-7.pkl
0.1 0.101694915254
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.01-realization-9.pkl
0.1 0.101694915254
Process Consumer-7:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.03-realization-9.pkl
0.1 0.101694915254
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.0-realization-5.pkl
0.1 0.101694915254
Process Consumer-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.0-realization-7.pkl
0.1 0.101694915254
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.0-realization-0.pkl
0.1 0.101694915254
    answer = next_task()
Process Consumer-29:
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
Traceback (most recent call last):
AttributeError: 'Task_generate_rf' object has no attribute 'E'
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.07-realization-9.pkl
0.1 0.101694915254
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Process Consumer-35:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Process Consumer-48:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.07-realization-7.pkl
0.1 0.101694915254
Process Consumer-36:
Process Consumer-34:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Consumer-11:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Process Consumer-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Process Consumer-32:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
Process Consumer-23:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.05-realization-1.pkl
0.1 0.101694915254
AttributeError: 'Task_generate_rf' object has no attribute 'E'
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.01-realization-0.pkl
0.1 0.101694915254
    answer = next_task()
Process Consumer-3:
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
Process Consumer-18:
    E_Y = [e for e in self.E if not E_X.has_key(e)]
Traceback (most recent call last):
AttributeError: 'Task_generate_rf' object has no attribute 'E'
Traceback (most recent call last):
Process Consumer-42:
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    self.run()
Process Consumer-26:
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.0-realization-1.pkl
0.1 0.101694915254
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Process Consumer-21:
Traceback (most recent call last):
Process Consumer-8:
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Process Consumer-19:
    answer = next_task()
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
Traceback (most recent call last):
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
AttributeError: 'Task_generate_rf' object has no attribute 'E'
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    answer = next_task()
    E_Y = [e for e in self.E if not E_X.has_key(e)]
    E_Y = [e for e in self.E if not E_X.has_key(e)]
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
    answer = next_task()
AttributeError: 'Task_generate_rf' object has no attribute 'E'
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
AttributeError: 'Task_generate_rf' object has no attribute 'E'
AttributeError: 'Task_generate_rf' object has no attribute 'E'
    answer = next_task()
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.0-realization-2.pkl
0.1 0.101694915254
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.05-realization-4.pkl
0.1 0.101694915254
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.03-realization-8.pkl
0.1 0.101694915254
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
    self.run()
    E_Y = [e for e in self.E if not E_X.has_key(e)]
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
AttributeError: 'Task_generate_rf' object has no attribute 'E'
AttributeError: 'Task_generate_rf' object has no attribute 'E'
    E_Y = [e for e in self.E if not E_X.has_key(e)]
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
AttributeError: 'Task_generate_rf' object has no attribute 'E'
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.03-realization-0.pkl
0.1 0.101694915254
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.03-realization-2.pkl
0.1 0.101694915254
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.01-realization-7.pkl
0.1 0.101694915254
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.0-realization-6.pkl
0.1 0.101694915254
Process Consumer-40:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Process Consumer-39:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Process Consumer-47:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.07-realization-6.pkl
0.1 0.101694915254
Process Consumer-37:
Traceback (most recent call last):
Process Consumer-9:
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.05-realization-6.pkl
0.1 0.101694915254
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.05-realization-3.pkl
0.1 0.101694915254
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.05-realization-8.pkl
0.1 0.101694915254
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.03-realization-5.pkl
0.1 0.101694915254
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.07-realization-1.pkl
0.1 0.101694915254
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.0-realization-9.pkl
0.1 0.101694915254
Process Consumer-38:
Process Consumer-41:
Process Consumer-4:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
Process Consumer-45:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Consumer-43:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.0-realization-3.pkl
0.1 0.101694915254
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.07-realization-4.pkl
0.1 0.101694915254
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.07-realization-2.pkl
0.1 0.101694915254
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.05-realization-9.pkl
0.1 0.101694915254
    answer = next_task()
    answer = next_task()
    answer = next_task()
Process Consumer-5:
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
Process Consumer-44:
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
    E_Y = [e for e in self.E if not E_X.has_key(e)]
    E_Y = [e for e in self.E if not E_X.has_key(e)]
Traceback (most recent call last):
Traceback (most recent call last):
AttributeError: 'Task_generate_rf' object has no attribute 'E'
AttributeError: 'Task_generate_rf' object has no attribute 'E'
AttributeError: 'Task_generate_rf' object has no attribute 'E'
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
Process Consumer-46:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.0-realization-8.pkl
0.1 0.101694915254
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.01-realization-8.pkl
0.1 0.101694915254
    self.run()
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.05-realization-5.pkl
0.1 0.101694915254
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 92, in run
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
AttributeError: 'Task_generate_rf' object has no attribute 'E'
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.07-realization-0.pkl
0.1 0.101694915254
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.0-realization-4.pkl
0.1 0.101694915254
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.05-realization-7.pkl
0.1 0.101694915254
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.07-realization-5.pkl
0.1 0.101694915254
    answer = next_task()
  File "traffic-data-generator-advsarial-ex-multiCore.py", line 128, in __call__
    E_Y = [e for e in self.E if not E_X.has_key(e)]
AttributeError: 'Task_generate_rf' object has no attribute 'E'
/network/rit/lab/ceashpc/adil/data/adv_csl/Jan2/traffic/random_flip/philly//network_philly_weekday_0_hour_8_refspeed_0.6-testratio-0.1-gamma-0.07-realization-3.pkl
0.1 0.101694915254
